# configs/main.yaml

data_settings:
  ticker: "SPY"
  start_date: "2010-01-01"
  end_date: "2024-01-01"

backtest_settings:
  strategy_name: "SentimentLSTMStrategy"
  strategy_module: "sentiment_lstm"
  n_splits: 10

# Nova seção para regras de trading
trading_rules:
  stop_loss_pct: 0.02  # Stop loss de 2%
  take_profit_pct: 0.04 # Take profit de 4%

reporting_settings:
  output_path: "reports/report_slstm_stops_spy.html" # Novo nome para o relatório