"""Pydantic schemas for strict real-time monitor WebSocket payloads.

This module defines the canonical contract used by backend broadcast.
The schema is strict (`extra='forbid'`) to block malformed payloads
before they reach the frontend.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class OHLCVBlock(BaseModel):
    """Canonical OHLCV block for monitor payload."""

    model_config = ConfigDict(extra="forbid")

    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    volume: int = 0


class IndicatorsBlock(BaseModel):
    """Technical indicators block ready for UI rendering."""

    model_config = ConfigDict(extra="forbid")

    ema_9: float = 0.0
    ema_20: float = 0.0
    sma_20: float = 0.0
    sma_50: float = 0.0
    rsi_14: float = 0.0


class AnalysisBlock(BaseModel):
    """Market context analysis block with normalized defaults."""

    model_config = ConfigDict(extra="forbid")

    trend: str = "INDEFINIDO"
    trend_strength: str = "INDEFINIDO"
    support: float = 0.0
    resistance: float = 0.0
    pattern: str = "INDEFINIDO"
    rsi_condition: str = "INDEFINIDO"


class MLBlock(BaseModel):
    """ML inference block with strict probability normalization."""

    model_config = ConfigDict(extra="forbid")

    signal: str = "HOLD"
    direction: str = "HOLD"
    probability: float = Field(default=0.0, ge=0.0)

    @field_validator("signal", "direction", mode="before")
    @classmethod
    def normalize_upper_signal(cls, value: Any) -> str:
        """Normalize signal-like fields to uppercase strings."""
        return str(value or "HOLD").upper()

    @field_validator("probability", mode="before")
    @classmethod
    def normalize_probability(cls, value: Any) -> float:
        """Normalize invalid/null probabilities to safe float values."""
        if value is None:
            return 0.0

        probability = float(value)
        if probability < 0.0:
            return 0.0
        return probability


class DecisionBlock(BaseModel):
    """Decision block generated by strategy validation."""

    model_config = ConfigDict(extra="forbid")

    signal_valid: bool = False
    validation_reason: str = "Sem validação"
    status: str = "NÃO VALIDADO"
    severity: str = "TICK"


class MonitorPayload(BaseModel):
    """Canonical strict payload for monitor WebSocket broadcast."""

    model_config = ConfigDict(extra="forbid")

    schema_version: str | None = None
    timestamp: datetime
    ticker: str
    timeframe: str
    ohlcv: OHLCVBlock
    indicators: IndicatorsBlock
    analysis: AnalysisBlock
    ml: MLBlock
    decision: DecisionBlock

    @field_validator("ticker", "timeframe", mode="before")
    @classmethod
    def normalize_upper_fields(cls, value: Any) -> str:
        """Normalize ticker and timeframe to uppercase strings."""
        return str(value or "").upper()

    @classmethod
    def from_runtime_payload(cls, payload: dict[str, Any]) -> "MonitorPayload":
        """Instantiate and validate payload from runtime dictionary.

        Parameters
        ----------
        payload:
            Runtime dictionary produced by monitor engine.

        Returns
        -------
        MonitorPayload
            Strictly validated canonical payload.
        """
        return cls.model_validate(payload)
